In [1]:
import pandas as pd
from IPython.display import display

# 1. Configuration de l'affichage Pandas
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.unicode.east_asian_width', True)

# 2. Chargement du dataset (format JSON Lines)
file_path = r'C:\Users\USER\Desktop\pfe\dialogue\bigdata\dataset_final_nlp_v2.jsonl'

try:
    # Lecture avec lines=True
    df = pd.read_json(file_path, lines=True)

    # Nettoyage des noms de colonnes
    df.columns = [col.split('.')[-1] for col in df.columns]

    # 3. Correction globale de la faute de frappe
    # On inclut TOUTES les colonnes susceptibles de contenir le mot
    TEXT_COLUMNS = [
        'instruction', 
        'issue_type', 
        'response',  
        'sentiment_label'
    ]

    for col in TEXT_COLUMNS:
        if col in df.columns:
            # Conversion en string pour éviter les erreurs si la colonne contient des NaN
            df[col] = df[col].astype(str).str.replace('التجوال', 'الجوال', regex=False)
            # On remet les 'None' ou 'nan' en vrais NaN si nécessaire
            df[col] = df[col].replace(['None', 'nan'], pd.NA)
            df[col] = df[col].apply(lambda x: f"USER: عسلامة | {x}" if str(x).startswith("BOT:") else x)
            df['instruction'] = df['instruction'].apply(
            lambda x: x.replace('BOT: إن شاء الله نكونو فدناك', 'USER: يعطيك الصحة | BOT: إن شاء الله نكونو فدناك') 
            if 'BOT: إن شاء الله نكونو فدناك' in str(x) else x
            )

    print("✅ Correction 'التجوال' -> 'الجوال' terminée.")


    # 5. Affichage général
    print("✅ Aperçu du dataset (1000 premières lignes) :")
    display(df.head(1000)) 

    print("-" * 50)
    print(f"Structure : {df.shape[0]} lignes, {df.shape[1]} colonnes.")
    print("-" * 50)
    print(df.info())

except Exception as e:
    print(f"❌ Erreur lors du chargement ou du traitement : {e}")

✅ Correction 'التجوال' -> 'الجوال' terminée.
✅ Aperçu du dataset (1000 premières lignes) :

,client_name,location_wilaya,location_delegation,issue_type,service_type,suggested_action,sentiment_label,instruction,response
0,خديجة بالقاسم,المنستير,قصر هلال,عطل في الشبكة,5G/Réseau,تثبت من حالة الشبكة,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في قصر هلال، المنستير. مجمتش نخدم télétravail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.,"سامحنا خويا الغالي, فما ضغط كبير حالياً في المنستير وقاعدين نصلحو في العطب، تو يرجع مريغل."
1,ليلى بن سالم,القيروان,بوحجلة,مشكلة في الدفع,Administrative,إعادة تفعيل الخط,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: خلصت الفاتورة عبر تطبيق MyTT و لتو الخط مقصوص في القيروان. | BOT: عندك رقم المعاملة (numéro de transaction)؟ | USER: إي عندي، لحظة هاهو قدامي.,سامحنا، ساعات السيستيم ياخذ شوية وقت. اعطيني الرقم تو نرجعلك الخط يخدم فوراً.
2,أنيس المزيغي,نابل,الحمامات,مشكلة في الجوال,Mobile,تثبت من حالة التجوال,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: أنا لبرا وتوا الـ Roaming ميعملش كونيكسيون. | BOT: ثبت اللي الـ Données en itinérance مفعّلة في تليفونك؟ | USER: إي مفعلة، أما لتوا لا حب يمشي شي.,ثبت في الـ réglages، وإلا اعطيني رقمك نثبتلك في سرفيس الـ Roaming.
3,مراد بن عرفة,مدنين,جرجيس,عطل في الشبكة,5G/Réseau,تثبت من حالة الشبكة,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في جرجيس، مدنين. مجمتش نخدم télétra vail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.,"سامحنا خويا الغالي, فما ضغط كبير حالياً في مدنين وقاعدين نصلحو في العطب، تو يرجع مريغل."
4,سلمى بن عرفة,نابل,الحمامات,بطء في الانترنات,VDSL,اختبار سرعة التدفق,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الديبي في نابل يضحك، نخلص في برشا فلوس و الواصل شي يحشم. | BOT: عملت test de débit avant ما تطلبنا؟ | USER: إي عملت، واصلني 4 ميغا برك وأنا عامل 20.,واضح، بربي أعمل test de débit وابعثلنا capture، وجرب طفي الموديم و عاود شعلو.
...,...,...,...,...,...,...,...,...,...
995,كريم بن عرفة,تونس,حي الخضراء,انقطاع الانترنات,ADSL/Fixe,تشخيص تقني,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الأنترنت مقصوصة في حي الخضراء عندها 3 أيام. | BOT: ثبتلي بربي في الموديم يشعل بالأحمر؟ | USER: إي نعم، لومبة لوس (LOS) تشعل بالأحمر.,يا خويا سامحنا، أعطيني رقم الخط نثبتلك وين واصل المشكل.
996,مراد الطرابلسي,سليانة,مكثر,انقطاع الانترنات,ADSL/Fixe,تشخيص تقني,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الأنترنت مقصوصة في مكثر عندها 3 أيام. | BOT: ثبتلي بر بي في الموديم يشعل بالأحمر؟ | USER: إي نعم، لومبة لوس (LOS) تشعل بالأحمر.,يا خويا سامحنا، أعطيني رقم الخط نثبتلك وين واصل المشكل.
997,هيثم الزغيدي,المنستير,قصر هلال,استفسار عن التغطية,Fibre Optique,تثبت من تغطية الفيبر,محايد,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: وقتاش ناوين تسيبو الفيبر في قصر هلال؟ عيينا من الـ ADSL. | BOT: تحب نثبتولك في التغطية في نهجك؟ | USER: إي ثبتلي يرحم والديك، رانا نستناو فيها بفارغ الصبر.,الفيبر قاعدين نركبو فيه بالتدريج في المنستير، خليلي رقمك تو نكلموك أول ما يوصل.
998,أنيس بن موسى,قبلي,دوز,اعتراض على الفاتورة,Billing,استخراج تفاصيل الفاتورة,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الفاتورة جاتني غالية برشا الشهر هذا في دوز. | BOT: تحب نثبتولك في ديتاي الاستهلاك؟ | USER: إي يرحم والديك، ثبتلي خاطر المبلغ مش عادي.,مرحبا بيك، تنجم تثبت في MyTT، وإلا اعطيني رقمك نثبتلك كان فما غلطة.
999,خديجة الدريدي,قابس,مارث,عطل في الشبكة,5G/Réseau,تثبت من حالة الشبكة,سلبي,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في مارث، قابس. مجمتش نخدم télétravail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.,"سامحنا خويا الغالي, فما ضغط كبير حالياً في قابس وقاعدين نصلحو في العطب، تو يرجع مريغل."

--------------------------------------------------
Structure : 6687 lignes, 9 colonnes.
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6687 entries, 0 to 6686
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_name          6648 non-null   object
 1   location_wilaya      6626 non-null   object
 2   location_delegation  6623 non-null   object
 3   issue_type           6656 non-null   object
 4   service_type         6640 non-null   object
 5   suggested_action     6629 non-null   object
 6   sentiment_label      6634 non-null   object
 7   instruction          6687 non-null   object
 8   response             6656 non-null   object
dtypes: object(9)
memory usage: 470.3+ KB
None

In [3]:
# On ne travaille QUE sur le texte brut
texts = df['instruction'].astype(str)

print("Exemples de réclamations :")
display(texts.head(10))

Exemples de réclamations :

0               USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في قصر هلال، المنستير. مجمتش نخدم télétravail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.
1                USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: خلصت الفاتورة عبر تطبيق MyTT و لتو الخط مقصوص في القيروان. | BOT: عندك رقم المعاملة (numéro de transaction)؟ | USER: إي عندي، لحظة هاهو قدامي.
2            USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: أنا لبرا وتوا الـ Roaming ميعملش كونيكسيون. | BOT: ثبت اللي الـ Données en itinérance مفعّلة في تليفونك؟ | USER: إي مفعلة، أما لتوا لا حب يمشي شي.
3                    USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في جرجيس، مدنين. مجمتش نخدم télétra vail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.
4          USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الديبي في نابل يضحك، نخلص في برشا فلوس و الواصل شي يحشم. | BOT: عملت test de débit avant ما تطلبنا؟ | USER: إي عملت، واصلني 4 ميغا برك وأنا عامل 20.
5                              USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الأنترنت مقصوصة في الشابة عندها 3 أيام. | BOT: ثبتلي بربي في الموديم يشعل بالأحمر؟ | USER: إي نعم، لومبة لوس (LOS) تشعل بالأحمر.
6      USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: كيفاش نجم نعرف قداش مازال عندي صولد في خطي في سوسة؟ | BOT: تلوج على الصولد الرئيسي ولا الـ bonus؟ | USER: نحب نعرف الصولد الكل، متع المكالمات والانترنت.
7                    USER:  عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: نحب نعرف شنوما أحسن عروض الـ 5G عندكم توة في قابس؟ | BOT: تلوج على عرض يومي ولا شهري؟ | USER: نلوج على forfait شهري يكون فيه برشا انترنت.
8      USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: وقتاش ناوين تسيبو الفيبر في السرس؟ عيينا من الـ ADSL. | BOT: تحب نثبتولك في التغطية في نهجك؟ | USER: إي ثبتلي يرحم والديك، رانا نستناو فيها بفارغ الصبر.
9    USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: يا تليكوم لتو لا جيتو ركبتو الفيكس في السرس. عندي شهر نستنى. | BOT: عندك رقم المطلب (numéro de demande)؟ | USER: عندي، المطلب تعدّى عندو برشا وما جاني حد.
Name: instruction, dtype: object

In [5]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)  # liens
    text = re.sub(r"@\w+", "", text)            # mentions
    text = re.sub(r"[^\w\s\u0600-\u06FF]", " ", text)  # ponctuation
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['instruction_clean'] = texts.apply(normalize_text)

display(df[['instruction', 'instruction_clean']].head(10))

,instruction,instruction_clean
0,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في قصر هلال، المنستير. مجمتش نخدم télétravail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الريزو طايح برشا في قصر هلال، المنستير مجمتش نخدم télétravail bot الخدمة موبيل ولا فيكس؟ user نحكي عالموبيل، التليفون ميفوتش شلطة وحدة
1,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: خلصت الفاتورة عبر تطبيق MyTT و لتو الخط مقصوص في القيروان. | BOT: عندك رقم المعاملة (numéro de transaction)؟ | USER: إي عندي، لحظة هاهو قدامي.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user خلصت الفاتورة عبر تطبيق mytt و لتو الخط مقصوص في القيروان bot عندك رقم المعاملة numéro de transaction ؟ user إي عندي، لحظة هاهو قدامي
2,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: أنا لبرا وتوا الـ Roaming ميعملش كونيكسيون. | BOT: ثبت اللي الـ Données en itinérance مفعّلة في تليفونك؟ | USER: إي مفعلة، أما لتوا لا حب يمشي شي.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user أنا لبرا وتوا الـ roaming ميعملش كونيكسيون bot ثبت اللي الـ données en itinérance مفعّلة في تليفونك؟ user إي مفعلة، أما لتوا لا حب يمشي شي
3,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الريزو طايح برشا في جرجيس، مدنين. مجمتش نخدم télétra vail. | BOT: الخدمة موبيل ولا فيكس؟ | USER: نحكي عالموبيل، التليفون ميفوتش شلطة وحدة.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الريزو طايح برشا في جرجيس، مدنين مجمتش نخدم télétra vail bot الخدمة موبيل ولا فيكس؟ user نحكي عالموبيل، التليفون ميفوتش شلطة وحدة
4,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الديبي في نابل يضحك، نخلص في برشا فلوس و الواصل شي يحشم. | BOT: عملت test de débit avant ما تطلبنا؟ | USER: إي عملت، واصلني 4 ميغا برك وأنا عامل 20.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الديبي في نابل يضحك، نخلص في برشا فلوس و الواصل شي يحشم bot عملت test de débit avant ما تطلبنا؟ user إي عملت، واصلني 4 ميغا برك وأنا عامل 20
5,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: الأنترنت مقصوصة في الشابة عندها 3 أيام. | BOT: ثبتلي بربي في الموديم يشعل بالأحمر؟ | USER: إي نعم، لومبة لوس (LOS) تشعل بالأحمر.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الأنترنت مقصوصة في الشابة عندها 3 أيام bot ثبتلي بربي في الموديم يشعل بالأحمر؟ user إي نعم، لومبة لوس los تشعل بالأحمر
6,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: كيفاش نجم نعرف قداش مازال عندي صولد في خطي في سوسة؟ | BOT: تلوج على الصولد الرئيسي ولا الـ bonus؟ | USER: نحب نعرف الصولد الكل، متع المكالمات والانترنت.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user كيفاش نجم نعرف قداش مازال عندي صولد في خطي في سوسة؟ bot تلوج على الصولد الرئيسي ولا الـ bonus؟ user نحب نعرف الصولد الكل، متع المكالمات والانترنت
7,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: نحب نعرف شنوما أحسن عروض الـ 5G عندكم توة في قابس؟ | BOT: تلوج على عرض يومي ولا شهري؟ | USER: نلوج على forfait شهري يكون فيه برشا انترنت.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user نحب نعرف شنوما أحسن عروض الـ 5g عندكم توة في قابس؟ bot تلوج على عرض يومي ولا شهري؟ user نلوج على forfait شهري يكون فيه برشا انترنت
8,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: وقتاش ناوين تسيبو الفيبر في السرس؟ عيينا من الـ ADSL. | BOT: تحب نثبتولك في التغطية في نهجك؟ | USER: إي ثبتلي يرحم والديك، رانا نستناو فيها بفارغ الصبر.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user وقتاش ناوين تسيبو الفيبر في السرس؟ عيينا من الـ adsl bot تحب نثبتولك في التغطية في نهجك؟ user إي ثبتلي يرحم والديك، رانا نستناو فيها بفارغ الصبر
9,USER: عسلامة | BOT: مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ | USER: يا تليكوم لتو لا جيتو ركبتو الفيكس في السرس. عندي شهر نستنى. | BOT: عندك رقم المطلب (numéro de demande)؟ | USER: عندي، المطلب تعدّى عندو برشا وما جاني حد.,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user يا تليكوم لتو لا جيتو ركبتو الفيكس في السرس عندي شهر نستنى bot عندك رقم المطلب numéro de demande ؟ user عندي، المطلب تعدّى عندو برشا وما جاني حد

In [7]:
# Vérification rapide de la présence de caractères arabes
def contains_arabic(text):
    return bool(re.search(r'[\u0600-\u06FF]', text))

df['contains_arabic'] = df['instruction_clean'].apply(contains_arabic)

df['contains_arabic'].value_counts()

contains_arabic
True    6687
Name: count, dtype: int64

In [9]:
def tokenize(text):
    return text.split()

df['tokens'] = df['instruction_clean'].apply(tokenize)

display(df[['instruction_clean', 'tokens']].head(5))

,instruction_clean,tokens
0,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الريزو طايح برشا في قصر هلال، المنستير مجمتش نخدم télétravail bot الخدمة موبيل ولا فيكس؟ user نحكي عالموبيل، التليفون ميفوتش شلطة وحدة,"[user, عسلامة, bot, مرحبا, بيك, في, تليكوم،, كيفاش, نجم, نعاونك؟, user, الريزو, طايح, برشا, في, قصر, هلال،, المنستير, مجمتش, نخدم, télétravail, bot, الخدمة, موبيل, ولا, فيكس؟, user, نحكي, عالموبيل،, التليفون, ميفوتش, شلطة, وحدة]"
1,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user خلصت الفاتورة عبر تطبيق mytt و لتو الخط مقصوص في القيروان bot عندك رقم المعاملة numéro de transaction ؟ user إي عندي، لحظة هاهو قدامي,"[user, عسلامة, bot, مرحبا, بيك, في, تليكوم،, كيفاش, نجم, نعاونك؟, user, خلصت, الفاتورة, عبر, تطبيق, mytt, و, لتو, الخط, مقصوص, في, القيروان, bot, عندك, رقم, المعاملة, numéro, de, transaction, ؟, user, إي, عندي،, لحظة, هاهو, قدامي]"
2,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user أنا لبرا وتوا الـ roaming ميعملش كونيكسيون bot ثبت اللي الـ données en itinérance مفعّلة في تليفونك؟ user إي مفعلة، أما لتوا لا حب يمشي شي,"[user, عسلامة, bot, مرحبا, بيك, في, تليكوم،, كيفاش, نجم, نعاونك؟, user, أنا, لبرا, وتوا, الـ, roaming, ميعملش, كونيكسيون, bot, ثبت, اللي, الـ, données, en, itinérance, مفعّلة, في, تليفونك؟, user, إي, مفعلة،, أما, لتوا, لا, حب, يمشي, شي]"
3,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الريزو طايح برشا في جرجيس، مدنين مجمتش نخدم télétra vail bot الخدمة موبيل ولا فيكس؟ user نحكي عالموبيل، التليفون ميفوتش شلطة وحدة,"[user, عسلامة, bot, مرحبا, بيك, في, تليكوم،, كيفاش, نجم, نعاونك؟, user, الريزو, طايح, برشا, في, جرجيس،, مدنين, مجمتش, نخدم, télétra, vail, bot, الخدمة, موبيل, ولا, فيكس؟, user, نحكي, عالموبيل،, التليفون, ميفوتش, شلطة, وحدة]"
4,user عسلامة bot مرحبا بيك في تليكوم، كيفاش نجم نعاونك؟ user الديبي في نابل يضحك، نخلص في برشا فلوس و الواصل شي يحشم bot عملت test de débit avant ما تطلبنا؟ user إي عملت، واصلني 4 ميغا برك وأنا عامل 20,"[user, عسلامة, bot, مرحبا, بيك, في, تليكوم،, كيفاش, نجم, نعاونك؟, user, الديبي, في, نابل, يضحك،, نخلص, في, برشا, فلوس, و, الواصل, شي, يحشم, bot, عملت, test, de, débit, avant, ما, تطلبنا؟, user, إي, عملت،, واصلني, 4, ميغا, برك, وأنا, عامل, 20]"

In [11]:
semantic_features = df['instruction_clean']

print("✅ Analyse sémantique terminée.")

✅ Analyse sémantique terminée.

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import numpy as np

VECTORISATION DU TEXTE (instruction)

In [15]:

# Nettoyage minimal
df['instruction'] = df['instruction'].astype(str).fillna("")

# Vectorisation TF-IDF (adaptée texte court + multilingue)
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    analyzer='word'
)

X_tfidf = tfidf.fit_transform(df['instruction_clean'])

X.4.1 Apprentissage du type de réclamation (issue_type)

In [19]:
import pandas as pd
import re

def final_perfect_clean(text):
    if pd.isna(text): return text
    
    # 1. Normalisation de base
    text = str(text).lower().strip()
    text = re.sub(r'[أإآ]', 'ا', text)
    text = re.sub(r'ة\b', 'ه', text)
    
    # 2. On définit les catégories "Cibles" (INCLUANT le mot corrigé : الجوال)
    target_categories = [
        "استفسار عن التغطيه", "استفسار عن العروض", "استفسار عن الرصيد",
        "مشكله في الجوال", "تاخير في التركيب", "مشكله في الدفع",
        "اعتراض على الفاتوره", "تبديل شريحه", "عطل في الشبكه",
        "انقطاع الانترنت", "عطب في الجهاز", "تغيير الخدمه",
        "بطء في الانترنت", "مشكله في اشاره الويفي"
    ]
    
    # Création du mapping sans espaces pour une comparaison robuste
    # On enlève aussi les voyelles ou signes si nécessaire, mais l'espace est le plus urgent
    mapping = {c.replace(" ", ""): c for c in target_categories}
    
    # 3. Nettoyage agressif de la clé de recherche (Suppression de TOUS les espaces)
    clean_key = re.sub(r'\s+', '', text) 
    clean_key = clean_key.replace("انترنات", "انترنت")
    clean_key = clean_key.replace("وايفاي", "ويفي")
    clean_key = clean_key.replace("التجوال", "الجوال") # Double sécurité
    
    # 4. Comparaison intelligente
    for key, original in mapping.items():
        # On vérifie si la clé sans espace correspond (ex: "مشكلهفيالجوال")
        if clean_key == key or key in clean_key or clean_key in key:
            return original
            
    # 5. Si aucune correspondance, on renvoie le texte avec des espaces normaux
    return re.sub(r'\s+', ' ', text).strip()

# Application
df['issue_type_clean'] = df['issue_type'].apply(final_perfect_clean)

# Vérification
print(df['issue_type_clean'].value_counts())

issue_type_clean
استفسار عن التغطيه       517
تاخير في التركيب         510
استفسار عن الرصيد        499
تبديل شريحه              497
اعتراض على الفاتوره      496
عطل في الشبكه            485
انقطاع الانترنت          484
عطب في الجهاز            482
مشكله في الدفع           478
مشكله في اشاره الويفي    474
بطء في الانترنت          471
استفسار عن العروض        469
تغيير الخدمه             458
مشكله في الجوال          336
Name: count, dtype: int64

In [21]:
# On garde uniquement les lignes valides
df_ml = df[['instruction_clean', 'issue_type_clean']].dropna()

print(df_ml.shape)

(6656, 2)

In [23]:
X_text = df_ml['instruction_clean']          # Entrée : texte brut
y_issue = df_ml['issue_type_clean']    # Sortie : type de réclamation

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1,2),
    max_features=10000
)

X_tfidf = tfidf.fit_transform(X_text)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y_issue,
    test_size=0.2,
    random_state=42,
    stratify=y_issue
)

In [29]:
from sklearn.linear_model import LogisticRegression

issue_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    n_jobs=-1
)

issue_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1)

In [31]:
import joblib

# Sauvegarde du modèle
joblib.dump(issue_model, "issue_model.pkl")

# Sauvegarde du vectorizer TF-IDF
joblib.dump(tfidf, "tfidf_issue.pkl")

print("✅ Modèle et vectorizer sauvegardés")

✅ Modèle et vectorizer sauvegardés

In [33]:
y_pred_issue = issue_model.predict(X_test)

In [35]:
from sklearn.metrics import classification_report, accuracy_score

print("📊 Résultats - Apprentissage du type de réclamation (issue_type)")
print("Accuracy :", accuracy_score(y_test, y_pred_issue))
print(classification_report(y_test, y_pred_issue))

📊 Résultats - Apprentissage du type de réclamation (issue_type)
Accuracy : 1.0
                       precision    recall  f1-score   support

   استفسار عن التغطيه       1.00      1.00      1.00       104
    استفسار عن الرصيد       1.00      1.00      1.00       100
    استفسار عن العروض       1.00      1.00      1.00        94
  اعتراض على الفاتوره       1.00      1.00      1.00        99
      انقطاع الانترنت       1.00      1.00      1.00        97
      بطء في الانترنت       1.00      1.00      1.00        94
     تاخير في التركيب       1.00      1.00      1.00       102
          تبديل شريحه       1.00      1.00      1.00        99
         تغيير الخدمه       1.00      1.00      1.00        92
        عطب في الجهاز       1.00      1.00      1.00        96
        عطل في الشبكه       1.00      1.00      1.00        97
مشكله في اشاره الويفي       1.00      1.00      1.00        95
      مشكله في الجوال       1.00      1.00      1.00        67
       مشكله في الدفع       1.00      1.00      1.00        96

             accuracy                           1.00      1332
            macro avg       1.00      1.00      1.00      1332
         weighted avg       1.00      1.00      1.00      1332

In [37]:
def predict_issue(text):
    vect = tfidf.transform([text])
    return issue_model.predict(vect)[0]

# Exemple
predict_issue("لريزو طايح برشا في بوحجلة")

'عطل في الشبكه'

X.4.2 Apprentissage du sentiment (sentiment_label)

In [40]:
import pandas as pd
import re

def normalize_sentiment_fixed(text):
    if pd.isna(text): return text
    
    # 1. Mise en texte et suppression des espaces internes
    text = str(text).replace(" ", "")
    
    # 2. Normalisation des caractères Arabes
    text = re.sub(r'[أإآ]', 'ا', text)
    text = re.sub(r'ة\b', 'ه', text)
    
    # 3. Recherche par mot-clé (sans espaces)
    if "سلبي" in text:
        return "سلبي"
    elif "محايد" in text:
        return "محايد"
    elif "ايجابي" in text:
        return "إيجابي"
    
    return text

# Application
df['sentiment_label'] = df['sentiment_label'].apply(normalize_sentiment_fixed)

# Vérification finale
print(df['sentiment_label'].value_counts())

sentiment_label
سلبي     4210
محايد    2424
Name: count, dtype: int64

In [42]:
# On garde uniquement les lignes utiles
df_sentiment = df[['instruction_clean', 'sentiment_label']].dropna()

print("📊 Distribution des sentiments :")
print(df_sentiment['sentiment_label'].value_counts())
print("Shape :", df_sentiment.shape)

📊 Distribution des sentiments :
sentiment_label
سلبي     4210
محايد    2424
Name: count, dtype: int64
Shape : (6634, 2)

In [44]:
X_text = df_sentiment['instruction_clean']        # Texte brut
y_sentiment = df_sentiment['sentiment_label']  # Label sentiment

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_sentiment = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1,2),
    max_features=10000
)

X_tfidf_sentiment = tfidf_sentiment.fit_transform(X_text)

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf_sentiment,
    y_sentiment,
    test_size=0.2,
    random_state=42,
    stratify=y_sentiment
)

In [48]:
from sklearn.linear_model import LogisticRegression

sentiment_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

sentiment_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [52]:
import joblib

# Sauvegarde du modèle
joblib.dump(sentiment_model, "sentiment_model.pkl")

# Sauvegarde du vectorizer TF-IDF
joblib.dump(tfidf_sentiment, "tfidf_sentiment.pkl")

print("✅ Modèle et vectorizer sauvegardés")

✅ Modèle et vectorizer sauvegardés

In [54]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = sentiment_model.predict(X_test)

print("📊 Résultats — Analyse du sentiment")
print(classification_report(y_test, y_pred))

print("📉 Matrice de confusion :")
print(confusion_matrix(y_test, y_pred))

📊 Résultats — Analyse du sentiment
              precision    recall  f1-score   support

        سلبي       1.00      1.00      1.00       842
       محايد       1.00      1.00      1.00       485

    accuracy                           1.00      1327
   macro avg       1.00      1.00      1.00      1327
weighted avg       1.00      1.00      1.00      1327

📉 Matrice de confusion :
[[842   0]
 [  0 485]]

X.4.3 Apprentissage du service impacté (service_type)

In [57]:
import pandas as pd
import re

def normalize_service_type_final(text):
    if pd.isna(text): return text
    
    # 1. Mise en minuscules et nettoyage strict
    # On retire tout ce qui n'est pas alphanumérique pour éviter les surprises
    text_raw = str(text).lower()
    clean_key = re.sub(r'[^a-z0-9]', '', text_raw)
    
    # 2. Mapping de correspondance (Ordre stratégique)
    # On traite les cas spécifiques "Réseau/G" en premier
    if "5g" in clean_key or "4g" in clean_key or "reseau" in clean_key:
        return "5G/Réseau"
    
    if "admin" in clean_key:
        return "Administrative"
    if "bill" in clean_key:
        return "Billing"
    if "vdsl" in clean_key:
        return "VDSL"
    if "adsl" in clean_key:
        return "ADSL"
    if "mobile" in clean_key:
        return "Mobile"
    if "fibre" in clean_key:
        return "Fibre"
    if "internet" in clean_key:
        return "Internet"
    if "fixe" in clean_key:
        return "Fixe"
    
    # Retourne le texte original propre si aucune règle ne correspond
    return text.strip().capitalize()

# Application
df['service_type_clean'] = df['service_type'].apply(normalize_service_type_final)

# Vérification
print(df['service_type_clean'].value_counts())

service_type_clean
ADSL              1942
Mobile            1337
5G/Réseau          946
VDSL               927
Fibre              516
Billing            493
Administrative     479
Name: count, dtype: int64

In [59]:
# On garde uniquement les colonnes utiles
df_service = df[['instruction_clean', 'service_type_clean']].dropna()

print(df_service.shape)
print(df_service['service_type_clean'].value_counts())

(6640, 2)
service_type_clean
ADSL              1942
Mobile            1337
5G/Réseau          946
VDSL               927
Fibre              516
Billing            493
Administrative     479
Name: count, dtype: int64

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

X_text = df_service['instruction_clean']
y_service = df_service['service_type_clean']

tfidf_service = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1,2),
    max_features=10000
)

X_tfidf_service = tfidf_service.fit_transform(X_text)

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf_service,
    y_service,
    test_size=0.2,
    random_state=42,
    stratify=y_service
)

In [65]:
from sklearn.linear_model import LogisticRegression

service_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

service_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [67]:
import joblib

# Sauvegarde du modèle
joblib.dump(service_model, "service_model.pkl")

# Sauvegarde du vectorizer TF-IDF
joblib.dump(tfidf_service, "tfidf_service.pkl")

print("✅ Modèle et vectorizer sauvegardés")

✅ Modèle et vectorizer sauvegardés

In [69]:
from sklearn.metrics import classification_report

y_pred_service = service_model.predict(X_test)

print("📊 Résultats - Service impacté (service_type)")
print(classification_report(y_test, y_pred_service))

📊 Résultats - Service impacté (service_type)
                precision    recall  f1-score   support

     5G/Réseau       1.00      1.00      1.00       189
          ADSL       1.00      1.00      1.00       388
Administrative       1.00      1.00      1.00        96
       Billing       1.00      1.00      1.00        99
         Fibre       1.00      1.00      1.00       103
        Mobile       1.00      1.00      1.00       267
          VDSL       1.00      1.00      1.00       186

      accuracy                           1.00      1328
     macro avg       1.00      1.00      1.00      1328
  weighted avg       1.00      1.00      1.00      1328

In [71]:
def predict_service_smart(text):
    # Prédiction ML
    vect = tfidf_service.transform([text])
    ml_pred = service_model.predict(vect)[0]

    # Règle sémantique prioritaire
    text_clean = text.lower()
    
    if "انترنت" in text_clean or "internet" in text_clean:
        return "Internet"

    return ml_pred

In [73]:
predict_service_smart("الانترنت بطئ برشا و ما نجمش نخدم")

'Internet'

In [75]:
predict_service_smart("لريزو طايح برشا في بوحجلة")

'5G/Réseau'

X.4.4 Apprentissage de la localisation impactée
(location_wilaya, location_delegation)

In [78]:
import pandas as pd
import re

def final_geo_cleaner(text):
    if pd.isna(text): return text
    
    # 1. Normalisation Arabe de base
    text = str(text).lower().strip()
    text = re.sub(r'[أإآ]', 'ا', text)
    text = re.sub(r'ة\b', 'ه', text)
    
    # 2. Clé de comparaison : on supprime TOUT (espaces, shadda, etc.)
    # Cela transforme "م كثر" en "مكثر" et "القصري ن" en "القصرين"
    clean_key = re.sub(r'\s+', '', text)
    clean_key = re.sub(r'[ّ]', '', clean_key) # Optionnel: enlève les accents

    # 3. Liste de référence (versions sans espaces pour la comparaison)
    reference_names = [
        "تونس", "سوسه", "جندوبه", "صفاقس", "توزر", "بنزرت", "مدنين", "باجه", "نابل", "القيروان",
        "طريقتنيور", "طبرقه", "حمامسوسه", "منزلبورقيبه", "دقاش", "جرجيس", "تستور", 
        "حيالخضراء", "بوحجله", "الحمامات", "ساقيهالداير", "ساقيهالزيت", "سبيطله", 
        "سكره", "رادس", "مكثر", "الشابه", "الفحص", "الرقاب", "قصرهلال", "مارث", 
        "المتلوي", "السرس", "دوز", "غمراسن", "طبربه", "اريانه", "القصرين", "بنعرس", 
        "سليانه", "المهديه", "زغوان", "سيديبوزيد", "المنستير", "قابس", "الكاف", "قفصه", "منوبه", "قبلي", "تطاوين"
    ]
    
    # Dictionnaire pour restaurer les espaces corrects
    official_map = {
        "طريقتنيور": "طريق تنيور",
        "حمامسوسه": "حمّام سوسة",
        "منزلبورقيبه": "منزل بورقيبة",
        "حيالخضراء": "حي الخضراء",
        "ساقيهالداير": "ساقية الداير",
        "ساقيهالزيت": "ساقية الزيت",
        "قصرهلال": "قصر هلال",
        "سيديبوزيد": "سيدي بوزيد",
        "بنعرس": "بن عروس"
    }

    # 4. Matching de sécurité
    if clean_key in reference_names:
        # Si on a une version officielle avec espace, on l'utilise, sinon on rend la clé propre
        return official_map.get(clean_key, clean_key)
            
    # 5. Si aucune correspondance, on renvoie quand même la clé sans espaces parasites
    # (C'est ce qui règle le cas "م كثر" -> "مكثر")
    return clean_key

# Application
df['location_wilaya'] = df['location_wilaya'].apply(final_geo_cleaner)
df['location_delegation'] = df['location_delegation'].apply(final_geo_cleaner)

# Vérification
print(df['location_delegation'].value_counts())
print(df['location_wilaya'].value_counts())

location_delegation
سبيطله          322
سكره            313
رادس            310
مكثر            298
حي الخضراء      286
جرجيس           285
الفحص           284
الشابه          284
الرقاب          276
تستور           276
قصر هلال        275
مارث            275
المتلوي         273
طبرقه           268
السرس           265
بوحجله          264
حمّام سوسة      263
الحمامات        263
دوز             262
طريق تنيور      260
غمراسن          258
طبربه           255
دقاش            255
منزل بورقيبة    253
Name: count, dtype: int64
location_wilaya
تونس          433
سوسه          309
صفاقس         307
اريانه        302
القصرين       301
بنعروس        298
سليانه        286
مدنين         277
زغوان         275
المهديه       273
المنستير      265
سيدي بوزيد    265
باجه          263
قابس          261
الكاف         259
قفصه          257
نابل          255
منوبه         254
جندوبه        254
القيروان      252
قبلي          251
بنزرت         248
تطاوين        242
توزر          239
Name: count, dtype: int64

In [80]:
# ✅ Correction des incohérences Délégation ↔ Wilaya
# Certaines délégations du dataset sont rattachées à une mauvaise wilaya.
# Ce mapping officiel corrige location_wilaya en se basant sur location_delegation.

DELEGATION_TO_WILAYA = {
    # Tunis
    "طريق تنيور":        "تونس",
    "حي الخضراء":        "تونس",
    # Ariana
    "سكره":              "اريانه",
    # Ben Arous
    "بن عروس":           "بن عروس",
    "رادس":              "بن عروس",
    # Manouba
    "طبربه":             "منوبه",
    # Nabeul
    "الحمامات":          "نابل",
    # Zaghouan
    "الفحص":             "زغوان",
    # Bizerte
    "منزل بورقيبة":      "بنزرت",
    # Béja
    "تستور":             "باجه",
    # Jendouba
    "طبرقه":             "جندوبه",
    # Kef
    "السرس":             "الكاف",
    # Siliana
    "مكثر":              "سليانه",
    # Sousse
    "حمّام سوسة":        "سوسه",
    # Monastir
    "قصر هلال":          "المنستير",
    # Mahdia
    "الشابه":            "المهديه",
    # Sfax
    "ساقية الداير":      "صفاقس",
    "ساقية الزيت":       "صفاقس",
    # Kairouan
    "بوحجله":            "القيروان",
    # Kasserine
    "سبيطله":            "القصرين",
    # Sidi Bouzid
    "الرقاب":            "سيدي بوزيد",
    # Gabès
    "مارث":              "قابس",
    # Medenine
    "جرجيس":             "مدنين",
    # Tataouine
    "غمراسن":            "تطاوين",
    # Gafsa
    "المتلوي":           "قفصه",
    # Tozeur
    "دقاش":              "توزر",
    # Kebili
    "دوز":               "قبلي",
}

def fix_wilaya_from_delegation(row):
    delegation = row['location_delegation']
    wilaya     = row['location_wilaya']
    correct_wilaya = DELEGATION_TO_WILAYA.get(str(delegation))
    if correct_wilaya and correct_wilaya != str(wilaya):
        return correct_wilaya
    return wilaya

# Application
before_counts = df['location_wilaya'].value_counts().to_dict()
df['location_wilaya'] = df.apply(fix_wilaya_from_delegation, axis=1)
after_counts  = df['location_wilaya'].value_counts().to_dict()

# Rapport des corrections
corrections = {
    w: (after_counts.get(w, 0) - before_counts.get(w, 0))
    for w in set(list(before_counts.keys()) + list(after_counts.keys()))
    if after_counts.get(w, 0) != before_counts.get(w, 0)
}
print("✅ Corrections délégation → wilaya appliquées.")
if corrections:
    print("\n📊 Lignes modifiées par wilaya :")
    for w, delta in sorted(corrections.items(), key=lambda x: -abs(x[1])):
        sign = "+" if delta > 0 else ""
        print(f"   {w}: {sign}{delta}")
else:
    print("   Aucun écart détecté (données déjà cohérentes).")

✅ Corrections délégation → wilaya appliquées.

📊 Lignes modifiées par wilaya :
   بن عروس: +310
   صفاقس: -303
   بنعروس: -293
   تونس: +117
   سوسه: -44
   القصرين: +23
   قفصه: +19
   جندوبه: +17
   توزر: +16
   سليانه: +16
   قابس: +16
   تطاوين: +16
   قبلي: +15
   القيروان: +15
   باجه: +15
   المنستير: +14
   المهديه: +14
   اريانه: +13
   مدنين: +11
   سيدي بوزيد: +11
   الكاف: +10
   زغوان: +10
   بنزرت: +10
   نابل: +9
   منوبه: +4

In [82]:
# Dataset ML pour la localisation
df_geo = df[['instruction_clean', 'location_wilaya', 'location_delegation']].dropna()

print(df_geo.shape)

(6623, 3)

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_geo = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1,2),
    max_features=8000
)

X_geo = tfidf_geo.fit_transform(df_geo['instruction_clean'])

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

y_wilaya = df_geo['location_wilaya']

X_train, X_test, y_train, y_test = train_test_split(
    X_geo,
    y_wilaya,
    test_size=0.2,
    random_state=42,
    stratify=y_wilaya
)

wilaya_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

wilaya_model.fit(X_train, y_train)

y_pred = wilaya_model.predict(X_test)

print("📊 Résultats — Prédiction de la Wilaya")
print(classification_report(y_test, y_pred))

📊 Résultats — Prédiction de la Wilaya
              precision    recall  f1-score   support

      اريانه       1.00      0.97      0.98        63
     القصرين       1.00      0.98      0.99        64
    القيروان       0.45      1.00      0.62        53
       الكاف       1.00      0.98      0.99        53
    المنستير       1.00      0.95      0.97        55
     المهديه       1.00      0.89      0.94        57
        باجه       1.00      0.89      0.94        55
     بن عروس       1.00      0.89      0.94        62
       بنزرت       1.00      0.94      0.97        50
      تطاوين       1.00      0.94      0.97        51
        توزر       1.00      0.98      0.99        51
        تونس       0.98      0.94      0.96       109
      جندوبه       1.00      0.94      0.97        54
       زغوان       1.00      0.96      0.98        57
      سليانه       0.98      0.97      0.97        60
        سوسه       1.00      0.92      0.96        53
  سيدي بوزيد       1.00      0.95      0.97        55
        قابس       1.00      0.95      0.97        55
        قبلي       1.00      0.98      0.99        52
        قفصه       1.00      0.95      0.97        55
       مدنين       1.00      0.98      0.99        57
       منوبه       1.00      0.98      0.99        51
        نابل       1.00      0.89      0.94        53

    accuracy                           0.95      1325
   macro avg       0.97      0.95      0.96      1325
weighted avg       0.98      0.95      0.96      1325

In [87]:
y_delegation = df_geo['location_delegation']

X_train, X_test, y_train, y_test = train_test_split(
    X_geo,
    y_delegation,
    test_size=0.2,
    random_state=42,
    stratify=y_delegation
)

delegation_model = LogisticRegression(
    max_iter=1200,
    class_weight='balanced'
)

delegation_model.fit(X_train, y_train)

y_pred = delegation_model.predict(X_test)

print("📊 Résultats — Prédiction de la Délégation")
print(classification_report(y_test, y_pred))

📊 Résultats — Prédiction de la Délégation
              precision    recall  f1-score   support

    الحمامات       1.00      0.87      0.93        53
      الرقاب       0.45      1.00      0.62        55
       السرس       1.00      0.96      0.98        53
      الشابه       0.98      0.96      0.97        57
       الفحص       1.00      0.89      0.94        57
     المتلوي       1.00      0.95      0.97        55
      بوحجله       1.00      0.96      0.98        53
       تستور       1.00      0.95      0.97        55
       جرجيس       1.00      1.00      1.00        57
  حمّام سوسة       1.00      0.91      0.95        53
  حي الخضراء       1.00      0.89      0.94        57
        دقاش       1.00      0.92      0.96        51
         دوز       1.00      0.96      0.98        52
        رادس       1.00      0.92      0.96        62
      سبيطله       1.00      0.95      0.98        64
        سكره       0.97      0.94      0.95        63
       طبربه       1.00      0.98      0.99        51
       طبرقه       0.98      0.94      0.96        54
  طريق تنيور       1.00      0.98      0.99        52
      غمراسن       1.00      0.96      0.98        51
    قصر هلال       1.00      0.96      0.98        55
        مارث       1.00      0.95      0.97        55
        مكثر       0.98      0.95      0.97        60
منزل بورقيبة       1.00      0.96      0.98        50

    accuracy                           0.95      1325
   macro avg       0.97      0.95      0.95      1325
weighted avg       0.97      0.95      0.95      1325

In [88]:
def predict_wilaya(text):
    vect = tfidf_geo.transform([text])
    return wilaya_model.predict(vect)[0]

In [90]:
def predict_delegation(text):
    vect = tfidf_geo.transform([text])
    return delegation_model.predict(vect)[0]

In [94]:
predict_wilaya("لريزو طايح برشا في بوحجلة")

'القيروان'

In [96]:
predict_delegation("الانترنت مقطوع في بوحجلة من البارح")

'بوحجله'

X.5 Apprentissage des actions et réponses associées

In [99]:
import re
import pandas as pd

# 1. On crée un dictionnaire de référence "propre" (SANS ESPACES) -> "Label correct"
raw_mapping = {
    'إعادة تفعيل الخط': 'إعادة تفعيل الخط',
    'تثبت من حالة الجوال': 'تثبت من حالة الجوال',
    'متابعة حالة الطلب': 'متابعة حالة الطلب',
    'تثبت من تغطية الفيبر': 'تثبت من تغطية الفيبر',
    'تقديم معلومات عن العروض': 'تقديم معلومات عن العروض',
    'تثبت من حالة الشبكة': 'تثبت من حالة الشبكة',
    'اختبار سرعة التدفق': 'اختبار سرعة التدفق',
    'تشخيص تقني': 'تشخيص تقني',
    'تقديم كود USSD': 'تقديم كود USSD',
    'تبديل المودم': 'تبديل المودم',
    'تقديم نصيحة تقنية': 'تقديم نصيحة تقنية',
    'استخراج تفاصيل الفاتورة': 'استخراج تفاصيل الفاتورة',
    'تحويل نوع الخدمة': 'تحويل نوع الخدمة',
    'مد الحريف بموقع فرع': 'مد الحريف بموقع فرع'
}

# On génère un dictionnaire de mapping normalisé (clé sans espaces et sans Alif Hamza)
def normalize_key(t):
    if not isinstance(t, str): return ""
    t = re.sub(r'\s+', '', t) # Supprime tous les espaces
    t = t.replace('أ', 'ا').replace('إ', 'ا').replace('آ', 'ا') # Normalise les Alif
    t = t.replace('التجوال', 'الجوال') # Gestion spécifique de votre cas
    return t

normalized_labels = {normalize_key(k): v for k, v in raw_mapping.items()}

# 2. Fonction de nettoyage intelligente
def clean_label_robust(text):
    if pd.isna(text) or str(text).strip().lower() == 'none':
        return None
    
    # Normalisation de la donnée entrante (on enlève tout espace)
    current_key = normalize_key(str(text))
    
    # On cherche dans notre dictionnaire normalisé
    return normalized_labels.get(current_key, text)

# 3. Application sur les colonnes
cols_to_fix = ['suggested_action', 'issue_type_clean', 'sentiment_label', 'service_type_clean']

for col in cols_to_fix:
    if col in df.columns:
        df[col] = df[col].apply(clean_label_robust)

# Vérification
print(f"✅ Classes finales : {df['suggested_action'].nunique()}")
print(df['suggested_action'].value_counts())

✅ Classes finales : 14
suggested_action
تثبت من تغطية الفيبر       517
متابعة حالة الطلب          510
تقديم كود USSD             500
مد الحريف بموقع فرع        496
استخراج تفاصيل الفاتورة    490
تثبت من حالة الشبكة        482
تشخيص تقني                 481
تبديل المودم               477
إعادة تفعيل الخط           473
تقديم نصيحة تقنية          472
اختبار سرعة التدفق         471
تقديم معلومات عن العروض    467
تحويل نوع الخدمة           456
تثبت من حالة الجوال        337
Name: count, dtype: int64

In [101]:
# Sélection des colonnes utiles pour la stratégie
df_strategy = df[[
    'issue_type_clean',
    'sentiment_label',
    'service_type_clean',
    'suggested_action',
    'response'
]].dropna().copy()

print(df_strategy.shape)
df_strategy.head()

(6467, 5)

,issue_type_clean,sentiment_label,service_type_clean,suggested_action,response
0,عطل في الشبكه,سلبي,5G/Réseau,تثبت من حالة الشبكة,"سامحنا خويا الغالي, فما ضغط كبير حالياً في المنستير وقاعدين نصلحو في العطب، تو يرجع مريغل."
1,مشكله في الدفع,سلبي,Administrative,إعادة تفعيل الخط,سامحنا، ساعات السيستيم ياخذ شوية وقت. اعطيني الرقم تو نرجعلك الخط يخدم فوراً.
2,مشكله في الجوال,سلبي,Mobile,تثبت من حالة الجوال,ثبت في الـ réglages، وإلا اعطيني رقمك نثبتلك في سرفيس الـ Roaming.
3,عطل في الشبكه,سلبي,5G/Réseau,تثبت من حالة الشبكة,"سامحنا خويا الغالي, فما ضغط كبير حالياً في مدنين وقاعدين نصلحو في العطب، تو يرجع مريغل."
4,بطء في الانترنت,سلبي,VDSL,اختبار سرعة التدفق,واضح، بربي أعمل test de débit وابعثلنا capture، وجرب طفي الموديم و عاود شعلو.

In [103]:
df_strategy['context_key'] = (
    df_strategy['issue_type_clean'] + " | " +
    df_strategy['sentiment_label'] + " | " +
    df_strategy['service_type_clean']
)

df_strategy[['context_key', 'suggested_action', 'response']].head()

,context_key,suggested_action,response
0,عطل في الشبكه | سلبي | 5G/Réseau,تثبت من حالة الشبكة,"سامحنا خويا الغالي, فما ضغط كبير حالياً في المنستير وقاعدين نصلحو في العطب، تو يرجع مريغل."
1,مشكله في الدفع | سلبي | Administrative,إعادة تفعيل الخط,سامحنا، ساعات السيستيم ياخذ شوية وقت. اعطيني الرقم تو نرجعلك الخط يخدم فوراً.
2,مشكله في الجوال | سلبي | Mobile,تثبت من حالة الجوال,ثبت في الـ réglages، وإلا اعطيني رقمك نثبتلك في سرفيس الـ Roaming.
3,عطل في الشبكه | سلبي | 5G/Réseau,تثبت من حالة الشبكة,"سامحنا خويا الغالي, فما ضغط كبير حالياً في مدنين وقاعدين نصلحو في العطب، تو يرجع مريغل."
4,بطء في الانترنت | سلبي | VDSL,اختبار سرعة التدفق,واضح، بربي أعمل test de débit وابعثلنا capture، وجرب طفي الموديم و عاود شعلو.

In [105]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_action = TfidfVectorizer(
    analyzer='word',
    ngram_range=(1,2),
    max_features=3000
)

X_action = tfidf_action.fit_transform(df_strategy['context_key'])
y_action = df_strategy['suggested_action']

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X_action, y_action,
    test_size=0.2,
    random_state=42,
    stratify=y_action
)

action_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

action_model.fit(X_train, y_train)

y_pred_action = action_model.predict(X_test)

print("📊 Résultats – Apprentissage des actions")
print(classification_report(y_test, y_pred_action))

📊 Résultats – Apprentissage des actions
                         precision    recall  f1-score   support

       إعادة تفعيل الخط       1.00      1.00      1.00        94
     اختبار سرعة التدفق       1.00      1.00      1.00        92
استخراج تفاصيل الفاتورة       1.00      1.00      1.00        95
           تبديل المودم       1.00      1.00      1.00        94
   تثبت من تغطية الفيبر       1.00      1.00      1.00       101
    تثبت من حالة الجوال       1.00      1.00      1.00        65
    تثبت من حالة الشبكة       1.00      1.00      1.00        95
       تحويل نوع الخدمة       1.00      1.00      1.00        88
             تشخيص تقني       1.00      1.00      1.00        94
         تقديم كود USSD       1.00      1.00      1.00        97
تقديم معلومات عن العروض       1.00      1.00      1.00        91
      تقديم نصيحة تقنية       1.00      1.00      1.00        92
      متابعة حالة الطلب       1.00      1.00      1.00        99
    مد الحريف بموقع فرع       1.00      1.00      1.00        97

               accuracy                           1.00      1294
              macro avg       1.00      1.00      1.00      1294
           weighted avg       1.00      1.00      1.00      1294

In [109]:
response_counts = df_strategy['response'].value_counts()
valid_responses = response_counts[response_counts >= 10].index

df_resp = df_strategy[df_strategy['response'].isin(valid_responses)]

X_resp = tfidf_action.transform(df_resp['context_key'])
y_resp = df_resp['response']

response_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

response_model.fit(X_resp, y_resp)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [111]:
def predict_action(issue, sentiment, service):
    context = f"ISSUE_{issue} | SENT_{sentiment} | SERV_{service}"
    vect = tfidf_action.transform([context])
    return action_model.predict(vect)[0]

def predict_response(issue, sentiment, service):
    context = f"ISSUE_{issue} | SENT_{sentiment} | SERV_{service}"
    vect = tfidf_action.transform([context])
    return response_model.predict(vect)[0]

In [113]:
predict_action(
    issue="عطل في الشبكه",
    sentiment="سلبي",
    service="5G/Réseau"
)

'تثبت من حالة الشبكة'

In [115]:
predict_response(
    issue="عطل في الشبكه",
    sentiment="سلبي",
    service="5G/Réseau"
)

'سامحنا خويا الغالي, فما ضغط كبير حالياً في المنستير وقاعدين نصلحو في العطب، تو يرجع مريغل.'

X.6 Construction du moteur de décision intelligent

In [118]:
CRITICAL_ISSUES = [
    "عطل في الشبكه",
    "انقطاع الانترنت",
    "مشكله في الدفع",
    "اعتراض على الفاتوره"
]

NEGATIVE_SENTIMENT = "سلبي"

In [120]:
def decision_engine(row):
    issue     = row['issue_type_clean']
    sentiment = row['sentiment_label']
    action    = row['suggested_action']

    if action is None or str(action).strip() == "":
        return "escalade_agent_humain"

    if sentiment == NEGATIVE_SENTIMENT and issue in CRITICAL_ISSUES:
        return "escalade_agent_humain"

    return "resolution_automatique"

In [122]:
df['decision'] = df.apply(decision_engine, axis=1)
df['decision'].value_counts()

decision
resolution_automatique    4721
escalade_agent_humain     1966
Name: count, dtype: int64

X.7 Production des sorties IA et préparation des couches supérieures

1️⃣ Sécurisation des valeurs

In [126]:
def safe_value(val, default="غير محدد"):
    if val is None or str(val).strip().lower() in ["none", "nan", ""]:
        return default
    return val

In [128]:
def end_conversation_message():
    return "إن شاء الله نكونو فدناك، وإذا عندك أي استفسار آخر مرحبا بيك في أي وقت."

2️⃣ Sortie IA structurée

In [131]:
def generate_ai_output(row):
    return {
        "issue_type": safe_value(row['issue_type_clean']),
        "service_type": safe_value(row['service_type_clean']),
        "sentiment": safe_value(row['sentiment_label']),
        "region": safe_value(row['location_wilaya']),
        "recommended_action": safe_value(row['suggested_action']),
        "decision": safe_value(row['decision'], "resolution_automatique"),
        "end_message": end_conversation_message()
    }

3️⃣ Test final (comme un vrai système)

In [134]:
test_row = {
    "issue_type_clean": "عطل في الشبكه",
    "service_type_clean": "4G/Réseau",
    "sentiment_label": "سلبي",
    "location_wilaya": "القيروان",
    "suggested_action": "تثبت من حالة الشبكة",
    "decision": "escalade_agent_humain"
}

test_df = pd.DataFrame([test_row])
print(test_df.apply(generate_ai_output, axis=1).iloc[0])

{'issue_type': 'عطل في الشبكه', 'service_type': '4G/Réseau', 'sentiment': 'سلبي', 'region': 'القيروان', 'recommended_action': 'تثبت من حالة الشبكة', 'decision': 'escalade_agent_humain', 'end_message': 'إن شاء الله نكونو فدناك، وإذا عندك أي استفسار آخر مرحبا بيك في أي وقت.'}

In [136]:
def generate_ai_output(text):
    """
    Génère une sortie IA structurée à partir d'une réclamation textuelle
    """

    # Vectorisation du texte
    vect_issue     = tfidf.transform([text])
    vect_sentiment = tfidf_sentiment.transform([text])
    vect_service   = tfidf_service.transform([text])

    # Prédictions ML
    issue_pred     = issue_model.predict(vect_issue)[0]
    sentiment_pred = sentiment_model.predict(vect_sentiment)[0]
    service_pred   = service_model.predict(vect_service)[0]

    # Décision intelligente
    if sentiment_pred == "سلبي" and issue_pred in [
        "عطل في الشبكه", "انقطاع الانترنت", "مشكله في الدفع"
    ]:
        decision = "escalade_agent_humain"
    else:
        decision = "reponse_automatique"

    # Sortie structurée
    output = {
        "issue_type": issue_pred,
        "service_type": service_pred,
        "sentiment": sentiment_pred,
        "decision": decision
    }

    return output

In [138]:
generate_ai_output("لريزو طايح برشا في بوحجلة و ما نجمش نخدم")

{'issue_type': 'عطل في الشبكه',
 'service_type': '5G/Réseau',
 'sentiment': 'سلبي',
 'decision': 'escalade_agent_humain'}